INSERT INTO tree_species (name, latin_name) VALUES
('Ash Spp.', 'Fraxinus Spp.'),
('Black Ash', 'Fraxinus Nigra'),
('Blue Ash', 'Fraxinus Quadrangulata'),
('Carolina Ash', 'Fraxinus Caroliniana'),
('Green Ash', 'Fraxinus Pennsylvanica'),
('Pumpkin Ash', 'Fraxinus Profunda'),
('Texas Ash', 'Fraxinus Texensis'),
('White Ash', 'Fraxinus Americana'),
('American Basswood', 'Tilia Americana'),
('Basswood Spp.', 'Tilia Spp.'),
('Carolina Basswood', 'Tilia Americana Var. Caroliniana'),
('White Basswood', 'Tilia Americana Var. Heterophylla'),
('American Beech', 'Fagus Grandifolia'),
('Black Walnut', 'Juglans Nigra'),
('Balsam Poplar', 'Populus Balsamifera'),
('Bigtooth Aspen', 'Populus Grandidentata'),
('Black Cottonwood', 'Populus Balsamifera Ssp. Trichocarpa'),
('Cottonwood And Poplar Spp.', 'Populus Spp.'),
('Eastern Cottonwood', 'Populus Deltoides'),
('Fremont Cottonwood', 'Populus Fremontii'),
('Lombardy Poplar', 'Populus Nigra'),
('Narrowleaf Cottonwood', 'Populus Angustifolia'),
('Plains Cottonwood', 'Populus Deltoides Ssp. Monilifera'),
('Quaking Aspen', 'Populus Tremuloides'),
('Silver Poplar', 'Populus Alba'),
('Swamp Cottonwood', 'Populus Heterophylla'),
('Baldcypress', 'Taxodium Distichum'),
('Pondcypress', 'Taxodium Ascendens'),
('Bigcone Douglas-fir', 'Pseudotsuga Macrocarpa'),
('Douglas-fir', 'Pseudotsuga Menziesii'),
('Carolina Hemlock', 'Tsuga Caroliniana'),
('Eastern Hemlock', 'Tsuga Canadensis'),
('Hemlock Spp.', 'Tsuga Spp.'),
('Ailanthus', 'Ailanthus Altissima'),
('Allegheny Chinkapin', 'Castanea Pumila'),
('American Chestnut', 'Castanea Dentata'),
('American Hornbeam, Musclewood', 'Carpinus Caroliniana'),
('American Mangrove', 'Rhizophora Mangle'),
('American Mountain-ash', 'Sorbus Americana'),
('American Plum', 'Prunus Americana'),
('Apple Spp.', 'Malus Spp.'),
('Arizona Walnut', 'Juglans Major'),
('Balsam Willow', 'Salix Pyrifolia'),
('Bay Spp.', 'Persea Spp.'),
('Bebb Willow', 'Salix Bebbiana'),
('Beeftree, Longleaf Blolly', 'Guapira Discolor'),
('Belah', 'Casuarina Lepidophloia'),
('Bigleaf Magnolia', 'Magnolia Macrophylla'),
('Black-mangrove', 'Avicennia Germinans'),
('Blue Oak', 'Quercus Douglasii'),
('Bluejack Oak', 'Quercus Incana'),
('Buttonwood-mangrove', 'Conocarpus Erectus'),
('Cabbage Palmetto', 'Sabal Palmetto'),
('California-laurel', 'Umbellularia Californica'),
('Camphortree', 'Cinnamomum Camphora'),
('Canada Plum', 'Prunus Nigra'),
('Cherry And Plum Spp.', 'Prunus Spp.'),
('Chestnut Spp.', 'Castanea Spp'),
('Chinaberry', 'Melia Azedarach'),
('Chinese Chestnut', 'Castanea Mollissima'),
('Chinese Tallowtree', 'Triadica Sebifera'),
('Chittamwood, Gum Bumelia', 'Sideroxylon Lanuginosum Ssp. Lanuginosum'),
('Chokecherry', 'Prunus Virginiana'),
('Citrus Spp.', 'Citrus Spp.'),
('Coastal Plain Willow', 'Salix Caroliniana'),
('Cockspur Hawthorn', 'Crataegus Crus-galli'),
('Common Serviceberry', 'Amelanchier Arborea'),
('Downy Hawthorn', 'Crataegus Mollis'),
('Dwarf Chinkapin Oak', 'Quercus Prinoides'),
('Eastern Hophornbeam', 'Ostrya Virginiana'),
('Eastern Redbud', 'Cercis Canadensis'),
('European Alder', 'Alnus Glutinosa'),
('European Mountain-ash', 'Sorbus Aucuparia'),
('Fishpoison Tree', 'Piscidia Piscipula'),
('Florida Poisontree', 'Metopium Toxiferum'),
('Florida Silver Palm', 'Coccothrinax Argentata'),
('Florida Strangler', 'Ficus Aurea'),
('Ginkgo, Maidenhair', 'Ginkgo Biloba'),
('Grand Eucalyptus', 'Eucalyptus Grandis'),
('Great Leucaene', 'Leucaena Pulverulenta'),
('Gumbo Limbo', 'Bursera Simaruba'),
('Hawthorn Spp.', 'Crataegus Spp.'),
('Java Plum', 'Syzygium Cumini'),
('Key Thatch Palm', 'Thrinax Morrisii'),
('Largeleaf Geigertree', 'Cordia Sebestena'),
('Mimosa, Silktree', 'Albizia Julibrissin'),
('Mountain Maple', 'Acer Spicatum'),
('Mountain-ash Spp.', 'Sorbus Spp.'),
('Northern Mountain-ash', 'Sorbus Decora'),
('Oak Spp.', 'Quercus Spp.'),
('Ogeechee Tupelo', 'Nyssa Ogeche'),
('Oregon Crab Apple', 'Malus Fusca'),
('Osage-orange', 'Maclura Pomifera'),
('Other Or Unknown Live Tree', 'Tree Unknown'),
('Other Palms', 'Family Arecaceae Not Listed Above'),
('Ozark Chinkapin', 'Castanea Pumila Var. Ozarkensis'),
('Pawpaw', 'Asimina Triloba'),
('Peach', 'Prunus Persica'),
('Peachleaf Willow', 'Salix Amygdaloides'),
('Persimmon Spp.', 'Diospyros Spp.'),
('Pin Cherry', 'Prunus Pensylvanica'),
('Pond-apple', 'Annona Glabra'),
('Prairie Crab Apple', 'Malus Ioensis'),
('Red Stopper', 'Eugenia Rhombea'),
('Roundleaf Serviceberry', 'Amelanchier Sanguinea'),
('Royal Palm Spp.', 'Roystonea Spp.'),
('Russian-olive', 'Elaeagnus Angustifolia'),
('Saltcedar', 'Tamarix Spp.'),
('Sassafras', 'Sassafras Albidum'),
('Scrub Oak', 'Quercus Ilicifolia'),
('Serviceberry Spp.', 'Amelanchier Spp.'),
('Sheoak Spp.', 'Casuarina Spp.'),
('Silverbell Spp.', 'Halesia Spp'),
('Smoketree', 'Cotinus Obovatus'),
('Sour Cherry, Domesticated', 'Prunus Cerasus'),
('Sourwood', 'Oxydendrum Arboreum'),
('Southern Catalpa', 'Catalpa Bignonioides'),
('Southern Crab Apple', 'Malus Angustifolia'),
('Southern Red Oak', 'Quercus Falcata'),
('Striped Maple', 'Acer Pensylvanicum'),
('Sweet Cherry, Domesticated', 'Prunus Avium'),
('Sweet Crab Apple', 'Malus Coronaria'),
('Sweetbay', 'Magnolia Virginiana'),
('Texas Persimmon', 'Diospyros Texana'),
('Tietongue, Pigeon-plum', 'Coccoloba Diversifolia'),
('Tungoil Tree', 'Vernicia Fordii'),
('Turkey Oak', 'Quercus Laevis'),
('Unknown Dead Hardwood', 'Tree Broadleaf'),
('Water-elm, Planertree', 'Planera Aquatica'),
('West Indian Mahogany', 'Swietenia Mahagoni'),
('Western Soapberry', 'Sapindus Saponaria Var. Drummondii'),
('White Bully, Willow Bustic', 'Sideroxylon Salicifolium'),
('White Willow', 'Salix Alba'),
('White-mangrove', 'Laguncularia Racemosa'),
('Willow Spp.', 'Salix Spp.'),
('Yellow Buckeye', 'Aesculus Flava'),
('Yellowwood', 'Cladrastis Kentukea'),
('Eastern White Pine', 'Pinus Strobus'),
('Red Pine', 'Pinus Resinosa'),
('Black Spruce', 'Picea Mariana'),
('Blue Spruce', 'Picea Pungens'),
('Brewer Spruce', 'Picea Breweriana'),
('Engelmann Spruce', 'Picea Engelmannii'),
('White Spruce', 'Picea Glauca'),
('Black Maple', 'Acer Nigrum'),
('Chalk Maple', 'Acer Leucoderme'),
('Florida Maple', 'Acer Barbatum'),
('Maple Spp.', 'Acer Spp.'),
('Norway Maple', 'Acer Platanoides'),
('Sugar Maple', 'Acer Saccharum'),
('Bitternut Hickory', 'Carya Cordiformis'),
('Black Hickory', 'Carya Texana'),
('Hickory Spp.', 'Carya Spp'),
('Mockernut Hickory', 'Carya Alba'),
('Nutmeg Hickory', 'Carya Myristiciformis'),
('Pecan', 'Carya Illinoinensis'),
('Pignut Hickory', 'Carya Glabra'),
('Red Hickory', 'Carya Ovalis'),
('Sand Hickory', 'Carya Pallida'),
('Scrub Hickory', 'Carya Floridana'),
('Shagbark Hickory', 'Carya Ovata'),
('Shellbark Hickory', 'Carya Laciniosa'),
('Southern Shagbark Hickory', 'Carya Carolinae-septentrionalis'),
('Water Hickory', 'Carya Aquatica'),
('Incense-cedar', 'Calocedrus Decurrens'),
('Jack Pine', 'Pinus Banksiana'),
('Loblolly Pine', 'Pinus Taeda'),
('Shortleaf Pine', 'Pinus Echinata'),
('Lodgepole Pine', 'Pinus Contorta'),
('Longleaf Pine', 'Pinus Palustris'),
('Slash Pine', 'Pinus Elliottii'),
('Blue Oak', 'Quercus Douglasii'),
('Bur Oak', 'Quercus Macrocarpa'),
('California Black Oak', 'Quercus Kelloggii'),
('California Live Oak', 'Quercus Agrifolia'),
('California White Oak', 'Quercus Lobata'),
('Canyon Live Oak', 'Quercus Chrysolepis'),
('Engelmann Oak', 'Quercus Engelmannii'),
('Interior Live Oak', 'Quercus Wislizeni'),
('Oregon White Oak', 'Quercus Garryana'),
('American Chestnut', 'Castanea Dentata'),
('American Holly', 'Ilex Opaca'),
('Birch Spp.', 'Betula Spp.'),
('Black Locust', 'Robinia Pseudoacacia'),
('Blackbead Ebony', 'Ebenopsis Ebano'),
('Catalpa Spp.', 'Catalpa Spp.'),
('Common Persimmon', 'Diospyros Virginiana'),
('Eucalyptus Spp.', 'Eucalyptus Spp.'),
('Flowering Dogwood', 'Cornus Florida'),
('Gray Birch', 'Betula Populifolia'),
('Honeylocust Gleditsia', 'Gleditsia Triacanthos'),
('Honeylocust Spp.', 'Gleditsia Spp.'),
('Kentucky Coffeetree', 'Gymnocladus Dioicus'),
('Mulberry Spp.', 'Morus Spp.'),
('Oak Spp.', 'Quercus Spp.'),
('Red Mulberry', 'Morus Rubra'),
('River Birch', 'Betula Nigra'),
('Rock Elm', 'Ulmus Thomasii'),
('Sweet Birch', 'Betula Lenta'),
('Texas Mulberry', 'Morus Microphylla'),
('Texas Sophora', 'Sophora Affinis'),
('Waterlocust Gleditsia', 'Gleditsia Aquatica'),
('White Mulberry', 'Morus Alba'),
('Yellowwood', 'Cladrastis Kentukea'),
('Alder Spp.', 'Alnus Spp.'),
('Allegheny Chinkapin', 'Castanea Pumila'),
('American Elm', 'Ulmus Americana'),
('American Sycamore', 'Platanus Occidentalis'),
('Birch Spp.', 'Betula Spp.'),
('Black Cherry', 'Prunus Serotina'),
('Black Willow', 'Salix Nigra'),
('Boxelder', 'Acer Negundo'),
('Buckeye, Horsechestnut Spp.', 'Aesculus Spp.'),
('Butternut', 'Juglans Cinerea'),
('Cabbage Palmetto', 'Sabal Palmetto'),
('Carolina Silverbell', 'Halesia Carolina'),
('Catalpa Spp.', 'Catalpa Spp.'),
('Cedar Elm', 'Ulmus Crassifolia'),
('Cucumbertree', 'Magnolia Acuminata'),
('Elm Spp.', 'Ulmus Spp.'),
('Gray Birch', 'Betula Populifolia'),
('Hackberry', 'Celtis Occidentalis'),
('Hackberry Spp.', 'Celtis Spp'),
('Kentucky Coffeetree', 'Gymnocladus Dioicus'),
('Loblolly-bay Gordonia', 'Gordonia Lasianthus'),
('Magnolia Spp.', 'Magnolia Spp.'),
('Maple Spp.', 'Acer Spp.'),
('Melaleuca', 'Melaleuca Quinquenervia'),
('Mountain Or Fraser Magnolia', 'Magnolia Fraseri'),
('Netleaf Hackberry', 'Celtis Laevigata Var. Reticulata'),
('Northern Catalpa', 'Catalpa Speciosa'),
('Ohio Buckeye', 'Aesculus Glabra'),
('Other Palms', 'Family Arecaceae Not Listed Above'),
('Ozark Chinkapin', 'Castanea Pumila Var. Ozarkensis'),
('Painted Buckeye', 'Aesculus Sylvatica'),
('Paper Birch', 'Betula Papyrifera'),
('Paulownia, Empress-tree', 'Paulownia Tomentosa'),
('Redbay', 'Persea Borbonia'),
('River Birch', 'Betula Nigra'),
('Sassafras', 'Sassafras Albidum'),
('September Elm', 'Ulmus Serotina'),
('Siberian Elm', 'Ulmus Pumila'),
('Silverbell Spp.', 'Halesia Spp'),
('Slippery Elm', 'Ulmus Rubra'),
('Southern Magnolia', 'Magnolia Grandiflora'),
('Sugarberry', 'Celtis Laevigata'),
('Sweetbay', 'Magnolia Virginiana'),
('Sycamore Spp.', 'Platanus Spp.'),
('Texas Buckeye', 'Aesculus Glabra Var. Arguta'),
('Texas Walnut', 'Juglans Microcarpa'),
('Two-wing Silverbell', 'Halesia Diptera'),
('Umbrella Magnolia', 'Magnolia Tripetala'),
('Walnut Spp.', 'Juglans Spp.'),
('Weeping Willow', 'Salix Sepulcralis'),
('White Willow', 'Salix Alba'),
('Willow Spp.', 'Salix Spp.'),
('Winged Elm', 'Ulmus Alata'),
('Yellow Buckeye', 'Aesculus Flava'),
('Ashe Juniper', 'Juniperus Ashei'),
('Atlantic White-cedar', 'Chamaecyparis Thyoides'),
('Austrian Pine', 'Pinus Nigra'),
('Blue Spruce', 'Picea Pungens'),
('Douglas-fir', 'Pseudotsuga Menziesii'),
('Eastern Redcedar', 'Juniperus Virginiana'),
('Engelmann Spruce', 'Picea Engelmannii'),
('Fraser Fir', 'Abies Fraseri'),
('Larch Spp.', 'Larix Spp.'),
('Northern White-cedar', 'Thuja Occidentalis'),
('Norway Spruce', 'Picea Abies'),
('Pine Spp.', 'Pinus Spp.'),
('Ponderosa Pine', 'Pinus Ponderosa'),
('Redcedar/juniper Spp.', 'Juniperus Spp.'),
('Sheoak Spp.', 'Casuarina Spp.'),
('Southern Redcedar', 'Juniperus Virginiana Var. Silicicola'),
('Tamarack', 'native'),
('Unknown Dead Conifer', 'Tree Evergreen'),
('White Fir', 'Abies Concolor'),
('Black Oak', 'Quercus Velutina'),
('Blackjack Oak', 'Quercus Marilandica'),
('Laurel Oak', 'Quercus Laurifolia'),
('Northern Pin', 'Quercus Ellipsoidalis'),
('Northern Red', 'Quercus Rubra'),
('Pin Oak', 'Quercus Palustris'),
('Scarlet Oak', 'Quercus Coccinea'),
('Shingle Oak', 'Quercus Imbricaria'),
('Southern Red Oak', 'Quercus Falcata'),
('Texas Red Oak', 'Quercus Texana'),
('Water Oak', 'Quercus Nigra'),
('Willow Oak', 'Quercus Phellos'),
('Gray Sheoak', 'Casuarina Glauca'),
('Other Or Unknown Live Tree', 'Tree Unknown'),
('Redwood', 'Sequoia Sempervirens'),
('Ailanthus', 'Ailanthus Altissima'),
('American Elm', 'Ulmus Americana'),
('American Holly', 'Ilex Opaca'),
('Apple Spp.', 'Malus Spp.'),
('Arizona Alder', 'Alnus Oblongifolia'),
('Arizona Madrone', 'Arbutus Arizonica'),
('Arizona Sycamore', 'Platanus Wrightii'),
('Arizona Walnut', 'Juglans Major'),
('Ash Spp.', 'Fraxinus Spp.'),
('Balsam Willow', 'Salix Pyrifolia'),
('Bigleaf Maple', 'Acer Macrophyllum'),
('Birch Spp.', 'Betula Spp.'),
('Bitter Cherry', 'Prunus Emarginata'),
('Black Locust', 'Robinia Pseudoacacia'),
('Black Willow', 'Salix Nigra'),
('Boxelder', 'Acer Negundo'),
('Buckeye, Horsechestnut Spp.', 'Aesculus Spp.'),
('Bur Oak', 'Quercus Macrocarpa'),
('California Buckeye', 'Aesculus Californica'),
('California Sycamore', 'Platanus Racemosa'),
('California-laurel', 'Umbellularia Californica'),
('Cherry And Plum Spp.', 'Prunus Spp.'),
('Chinkapin Oak', 'Quercus Muehlenbergii'),
('Chokecherry', 'Prunus Virginiana'),
('Eucalyptus Spp.', 'Eucalyptus Spp.'),
('Giant Chinkapin, Golden Chinkapin', 'Chrysolepis Chrysophylla Var. Chrysophylla'),
('Green Ash', 'Fraxinus Pennsylvanica'),
('Hackberry', 'Celtis Occidentalis'),
('Hawthorn Spp.', 'Crataegus Spp.'),
('Honeylocust Gleditsia', 'Gleditsia Triacanthos'),
('Maple Spp.', 'Acer Spp.'),
('Northern California Black Walnut', 'Juglans Hindsii'),
('Norway Maple', 'Acer Platanoides'),
('Oregon Ash', 'Fraxinus Latifolia'),
('Oregon Crab Apple', 'Malus Fusca'),
('Other Or Unknown Live Tree', 'Tree Unknown'),
('Pacific Dogwood', 'Cornus Nuttallii'),
('Pacific Madrone', 'Arbutus Menziesii'),
('Paper Birch', 'Betula Papyrifera'),
('Russian-olive', 'Elaeagnus Angustifolia'),
('Siberian Elm', 'Ulmus Pumila'),
('Southern California Black Walnut', 'Juglans Californica'),
('Sugarberry', 'Celtis Laevigata'),
('Sweet Cherry, Domesticated', 'Prunus Avium'),
('Sweetgum', 'Liquidambar Styraciflua'),
('Tanoak', 'Lithocarpus Densiflorus'),
('Tasmanian Bluegum', 'Eucalyptus Globulus'),
('Unknown Dead Hardwood', 'Tree Broadleaf'),
('Velvet Ash', 'Fraxinus Velutina'),
('Walnut Spp.', 'Juglans Spp.'),
('Water Birch', 'Betula Occidentalis'),
('Weeping Willow', 'Salix Sepulcralis'),
('White Alder', 'Alnus Rhombifolia'),
('White Willow', 'Salix Alba'),
('Willow Spp.', 'Salix Spp.'),
('Alaska Yellow-cedar', 'Chamaecyparis Nootkatensis'),
('Apache Pine', 'Pinus Engelmannii'),
('Arizona Cypress', 'Cupressus Arizonica'),
('Baker Or Modoc Cypress', 'Cupressus Bakeri'),
('Bishop Pine', 'Pinus Muricata'),
('California Torreya', 'nutmeg'),
('Chihuahuan Pine', 'Pinus Leiophylla'),
('Coulter Pine', 'Pinus Coulteri'),
('Cypress', 'Cupressus Spp.'),
('Foxtail Pine', 'Pinus Balfouriana'),
('Giant Sequoia', 'Sequoiadendron Giganteum'),
('Gray Or California Foothill Pine', 'Pinus Sabiniana'),
('Great Basin Bristlecone Pine', 'Pinus Longaeva'),
('Knobcone Pine', 'Pinus Attenuata'),
('Limber Pine', 'Pinus Flexilis'),
('Macnab''s Cypress', 'Cupressus Macnabiana'),
('Monterey Cypress', 'Cupressus Macrocarpa'),
('Monterey Pine', 'Pinus Radiata'),
('Mountain Hemlock', 'Tsuga Mertensiana'),
('Pacific Yew', 'Taxus Brevifolia'),
('Port-orford-cedar', 'Chamaecyparis Lawsoniana'),
('Rocky Mountain Bristlecone Pine', 'Pinus Aristata'),
('Sargent''s Cypress', 'Cupressus Sargentii'),
('Scotch Pine', 'Pinus Sylvestris'),
('Southwestern White Pine', 'Pinus Strobiformis'),
('Subalpine Larch', 'Larix Lyallii'),
('Unknown Dead Conifer', 'Tree Evergreen'),
('Washoe Pine', 'Pinus Washoensis'),
('Western Juniper', 'Juniperus Occidentalis'),
('Whitebark Pine', 'Pinus Albicaulis'),
('Chestnut Oak', 'Quercus Prinus'),
('Delta Post Oak', 'Quercus Similis'),
('Dwarf Live Oak', 'Quercus Minima'),
('Dwarf Post Oak', 'Quercus Margarettiae'),
('Live Oak', 'Quercus Virginiana'),
('Oglethorpe Oak', 'Quercus Oglethorpensis'),
('Overcup Oak', 'Quercus Lyrata'),
('Post Oak', 'Quercus Stellata'),
('Texas Olive', 'Cordia Boissieri'),
('Pitch Pine', 'Pinus Rigida'),
('Pond Pine', 'Pinus Serotina'),
('Sand Pine', 'Pinus Clausa'),
('Scotch Pine', 'Pinus Sylvestris'),
('Spruce Pine', 'Pinus Glabra'),
('Table Mountain Pine', 'Pinus Pungens'),
('Virginia Pine', 'Pinus Virginiana'),
('Arizona Pine', 'Pinus Arizonica'),
('Jeffrey Pine', 'Pinus Jeffreyi'),
('Ponderosa Pine', 'Pinus Ponderosa'),
('Red Alder', 'Alnus Rubra'),
('Redwood', 'Sequoia Sempervirens'),
('Buckley Oak', 'Quercus Buckleyi'),
('Cherrybark Oak', 'Quercus Pagoda'),
('Chisos Oak', 'Quercus Graciliformis'),
('Graves Oak', 'Quercus Gravesii'),
('Lacey Oak', 'Quercus Laceyi'),
('Northern Red', 'Quercus Rubra'),
('Shumard Oak', 'Quercus Shumardii'),
('Bur Oak', 'Quercus Macrocarpa'),
('Chinkapin Oak', 'Quercus Muehlenbergii'),
('Durand Oak', 'Quercus Sinuata Var. Sinuata'),
('Swamp Chestnut Oak', 'Quercus Michauxii'),
('Swamp White Oak', 'Quercus Bicolor'),
('White Oak', 'Quercus Alba'),
('Sitka Spruce', 'Picea Sitchensis'),
('Red Maple', 'Acer Rubrum'),
('Silver Maple', 'Acer Saccharinum'),
('Balsam Fir', 'Abies Balsamea'),
('Black Spruce', 'Picea Mariana'),
('Fir Spp.', 'Abies Spp.'),
('Red Spruce', 'Picea Rubens'),
('Spruce Spp.', 'Picea Spp.'),
('White Spruce', 'Picea Glauca'),
('Sugar Pine', 'Pinus Lambertiana'),
('Sweetgum', 'Liquidambar Styraciflua'),
('Acacia Spp.', 'Acacia Spp.'),
('American Mangrove', 'Rhizophora Mangle'),
('Avocado', 'Persea Americana'),
('Belah', 'Casuarina Lepidophloia'),
('Black Mulberry', 'Morus Nigra'),
('Black-mangrove', 'Avicennia Germinans'),
('Butterbough, Inkwood', 'Exothea Paniculata'),
('Buttonwood-mangrove', 'Conocarpus Erectus'),
('Camphortree', 'Cinnamomum Camphora'),
('Eucalyptus Spp.', 'Eucalyptus Spp.'),
('False Mastic', 'Sideroxylon Foetidissimum'),
('Florida Fiddlewood', 'Citharexylum Fruticosum'),
('Florida Poisontree', 'Metopium Toxiferum'),
('Grand Eucalyptus', 'Eucalyptus Grandis'),
('Gumbo Limbo', 'Bursera Simaruba'),
('Java Plum', 'Syzygium Cumini'),
('Largeleaf Geigertree', 'Cordia Sebestena'),
('Manchineel', 'Hippomane Mancinella'),
('Mango', 'Mangifera Indica'),
('Melaleuca', 'Melaleuca Quinquenervia'),
('Octopus Tree, Schefflera', 'Schefflera Actinophylla'),
('Other Or Unknown Live Tree', 'Tree Unknown'),
('Red Stopper', 'Eugenia Rhombea'),
('Sea Torchwood', 'Amyris Elemifera'),
('Swampmahogany Eucalyptus', 'Eucalyptus Robusta'),
('Sweet Acacia', 'Acacia Farnesiana'),
('Tamarind', 'Tamarindus Indica'),
('Tietongue, Pigeon-plum', 'Coccoloba Diversifolia'),
('Unknown Dead Hardwood', 'Tree Broadleaf'),
('West Indian Mahogany', 'Swietenia Mahagoni'),
('White Bully, Willow Bustic', 'Sideroxylon Salicifolium'),
('White Mulberry', 'Morus Alba'),
('White-mangrove', 'Laguncularia Racemosa'),
('Wild Banyantree, Shortleaf Fig', 'Ficus Citrifolia'),
('Coconut Palm', 'Cocos Nucifera'),
('California Red Fir', 'Abies Magnifica'),
('Corkbark Fir', 'Abies Lasiocarpa Var. Arizonica'),
('Grand Fir', 'Abies Grandis'),
('Noble Fir', 'Abies Procera'),
('Pacific Silver Fir', 'Abies Amabilis'),
('Shasta Red Fir', 'Abies Shastensis'),
('Subalpine Fir', 'Abies Lasiocarpa'),
('White Fir', 'Abies Concolor'),
('Blackgum', 'Nyssa Sylvatica'),
('Swamp Tupelo', 'Nyssa Biflora'),
('Tupelo Spp.', 'Nyssa Spp.'),
('Water Tupelo', 'Nyssa Aquatica'),
('Western Hemlock', 'Tsuga Heterophylla'),
('Western Larch', 'Larix Occidentalis'),
('Western Redcedar', 'Thuja Plicata'),
('Western White Pine', 'Pinus Monticola'),
('Acacia Spp.', 'Acacia Spp.'),
('Anacua Knockaway', 'Ehretia Anacua'),
('Arizona White Oak', 'Quercus Arizonica'),
('Bigtooth Maple', 'Acer Grandidentatum'),
('Bluewood', 'Condalia Hookeri'),
('California Buckeye', 'Aesculus Californica'),
('Curlleaf Mountain-mahogany', 'Cercocarpus Ledifolius'),
('Desert Ironwood', 'Olneya Tesota'),
('Emory Oak', 'Quercus Emoryi'),
('Gambel Oak', 'Quercus Gambeli'),
('Gray Oak', 'Quercus Grisea'),
('Honey Mesquite', 'Prosopis Glandulosa'),
('Mesquite Spp.', 'Prosopis Spp'),
('Mexican Blue Oak', 'Quercus Oblongifolia'),
('Netleaf Oak', 'Quercus Grisea'),
('New Mexico Locust', 'Robinia Neomexicana'),
('Oak Spp.', 'Quercus Spp.'),
('Rocky Mountain Maple', 'Acer Glabrum'),
('Screwbean Mesquite', 'Prosopis Pubescens'),
('Silverleaf Oak', 'Quercus Hypoleucoides'),
('Sweet Acacia', 'Acacia Farnesiana'),
('Texas Madrone', 'Arbutus Xalapensis'),
('Velvet Mesquite', 'Prosopis Velutina'),
('Willow Spp.', 'Salix Spp.'),
('Alligator Juniper', 'Juniperus Deppeana'),
('Arizona Pinyon Pine', 'Pinus Monophylla Var. Fallax'),
('Ashe Juniper', 'Juniperus Ashei'),
('Border Pinyon', 'Pinus Discolor'),
('California Juniper', 'Juniperus Californica'),
('Common Or Two-needle Pinyon', 'Pinus Edulis'),
('Drooping Juniper', 'Juniperus Flaccida'),
('Mexican Pinyon Pine', 'Pinus Cembroides'),
('Oneseed Juniper', 'Juniperus Monosperma'),
('Papershell Pinyon', 'Pinus Remota'),
('Pinchot Juniper', 'Juniperus Pinchotii'),
('Redberry Juniper', 'Juniperus Coahuilensis'),
('Rocky Mountain Juniper', 'Juniperus Scopulorum'),
('Singleleaf Pinyon', 'Pinus Monophylla'),
('Utah Juniper', 'Juniperus Osteosperma'),
('Yellow Birch', 'Betula Alleghaniensis'),
('Yellow-poplar', 'Liriodendron Tulipifera');