/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SellersImport } from './routes/sellers'
import { Route as LoginImport } from './routes/login'
import { Route as BuyersImport } from './routes/buyers'
import { Route as AuthImport } from './routes/_auth'
import { Route as IndexImport } from './routes/index'
import { Route as SellersSellerIdImport } from './routes/sellers/$sellerId'
import { Route as BuyersBuyerIdImport } from './routes/buyers/$buyerId'
import { Route as AuthProfileImport } from './routes/_auth.profile'
import { Route as SellersSellerIdWoodPiecesListImport } from './routes/sellers/$sellerId/wood-pieces-list'
import { Route as BuyersBuyerIdWoodPieceOffersListImport } from './routes/buyers/$buyerId/wood-piece-offers-list'

// Create/Update Routes

const SellersRoute = SellersImport.update({
  id: '/sellers',
  path: '/sellers',
  getParentRoute: () => rootRoute,
} as any)

const LoginRoute = LoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const BuyersRoute = BuyersImport.update({
  id: '/buyers',
  path: '/buyers',
  getParentRoute: () => rootRoute,
} as any)

const AuthRoute = AuthImport.update({
  id: '/_auth',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const SellersSellerIdRoute = SellersSellerIdImport.update({
  id: '/$sellerId',
  path: '/$sellerId',
  getParentRoute: () => SellersRoute,
} as any)

const BuyersBuyerIdRoute = BuyersBuyerIdImport.update({
  id: '/$buyerId',
  path: '/$buyerId',
  getParentRoute: () => BuyersRoute,
} as any)

const AuthProfileRoute = AuthProfileImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthRoute,
} as any)

const SellersSellerIdWoodPiecesListRoute =
  SellersSellerIdWoodPiecesListImport.update({
    id: '/wood-pieces-list',
    path: '/wood-pieces-list',
    getParentRoute: () => SellersSellerIdRoute,
  } as any)

const BuyersBuyerIdWoodPieceOffersListRoute =
  BuyersBuyerIdWoodPieceOffersListImport.update({
    id: '/wood-piece-offers-list',
    path: '/wood-piece-offers-list',
    getParentRoute: () => BuyersBuyerIdRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthImport
      parentRoute: typeof rootRoute
    }
    '/buyers': {
      id: '/buyers'
      path: '/buyers'
      fullPath: '/buyers'
      preLoaderRoute: typeof BuyersImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/sellers': {
      id: '/sellers'
      path: '/sellers'
      fullPath: '/sellers'
      preLoaderRoute: typeof SellersImport
      parentRoute: typeof rootRoute
    }
    '/_auth/profile': {
      id: '/_auth/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthProfileImport
      parentRoute: typeof AuthImport
    }
    '/buyers/$buyerId': {
      id: '/buyers/$buyerId'
      path: '/$buyerId'
      fullPath: '/buyers/$buyerId'
      preLoaderRoute: typeof BuyersBuyerIdImport
      parentRoute: typeof BuyersImport
    }
    '/sellers/$sellerId': {
      id: '/sellers/$sellerId'
      path: '/$sellerId'
      fullPath: '/sellers/$sellerId'
      preLoaderRoute: typeof SellersSellerIdImport
      parentRoute: typeof SellersImport
    }
    '/buyers/$buyerId/wood-piece-offers-list': {
      id: '/buyers/$buyerId/wood-piece-offers-list'
      path: '/wood-piece-offers-list'
      fullPath: '/buyers/$buyerId/wood-piece-offers-list'
      preLoaderRoute: typeof BuyersBuyerIdWoodPieceOffersListImport
      parentRoute: typeof BuyersBuyerIdImport
    }
    '/sellers/$sellerId/wood-pieces-list': {
      id: '/sellers/$sellerId/wood-pieces-list'
      path: '/wood-pieces-list'
      fullPath: '/sellers/$sellerId/wood-pieces-list'
      preLoaderRoute: typeof SellersSellerIdWoodPiecesListImport
      parentRoute: typeof SellersSellerIdImport
    }
  }
}

// Create and export the route tree

interface AuthRouteChildren {
  AuthProfileRoute: typeof AuthProfileRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthProfileRoute: AuthProfileRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface BuyersBuyerIdRouteChildren {
  BuyersBuyerIdWoodPieceOffersListRoute: typeof BuyersBuyerIdWoodPieceOffersListRoute
}

const BuyersBuyerIdRouteChildren: BuyersBuyerIdRouteChildren = {
  BuyersBuyerIdWoodPieceOffersListRoute: BuyersBuyerIdWoodPieceOffersListRoute,
}

const BuyersBuyerIdRouteWithChildren = BuyersBuyerIdRoute._addFileChildren(
  BuyersBuyerIdRouteChildren,
)

interface BuyersRouteChildren {
  BuyersBuyerIdRoute: typeof BuyersBuyerIdRouteWithChildren
}

const BuyersRouteChildren: BuyersRouteChildren = {
  BuyersBuyerIdRoute: BuyersBuyerIdRouteWithChildren,
}

const BuyersRouteWithChildren =
  BuyersRoute._addFileChildren(BuyersRouteChildren)

interface SellersSellerIdRouteChildren {
  SellersSellerIdWoodPiecesListRoute: typeof SellersSellerIdWoodPiecesListRoute
}

const SellersSellerIdRouteChildren: SellersSellerIdRouteChildren = {
  SellersSellerIdWoodPiecesListRoute: SellersSellerIdWoodPiecesListRoute,
}

const SellersSellerIdRouteWithChildren = SellersSellerIdRoute._addFileChildren(
  SellersSellerIdRouteChildren,
)

interface SellersRouteChildren {
  SellersSellerIdRoute: typeof SellersSellerIdRouteWithChildren
}

const SellersRouteChildren: SellersRouteChildren = {
  SellersSellerIdRoute: SellersSellerIdRouteWithChildren,
}

const SellersRouteWithChildren =
  SellersRoute._addFileChildren(SellersRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '': typeof AuthRouteWithChildren
  '/buyers': typeof BuyersRouteWithChildren
  '/login': typeof LoginRoute
  '/sellers': typeof SellersRouteWithChildren
  '/profile': typeof AuthProfileRoute
  '/buyers/$buyerId': typeof BuyersBuyerIdRouteWithChildren
  '/sellers/$sellerId': typeof SellersSellerIdRouteWithChildren
  '/buyers/$buyerId/wood-piece-offers-list': typeof BuyersBuyerIdWoodPieceOffersListRoute
  '/sellers/$sellerId/wood-pieces-list': typeof SellersSellerIdWoodPiecesListRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '': typeof AuthRouteWithChildren
  '/buyers': typeof BuyersRouteWithChildren
  '/login': typeof LoginRoute
  '/sellers': typeof SellersRouteWithChildren
  '/profile': typeof AuthProfileRoute
  '/buyers/$buyerId': typeof BuyersBuyerIdRouteWithChildren
  '/sellers/$sellerId': typeof SellersSellerIdRouteWithChildren
  '/buyers/$buyerId/wood-piece-offers-list': typeof BuyersBuyerIdWoodPieceOffersListRoute
  '/sellers/$sellerId/wood-pieces-list': typeof SellersSellerIdWoodPiecesListRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/buyers': typeof BuyersRouteWithChildren
  '/login': typeof LoginRoute
  '/sellers': typeof SellersRouteWithChildren
  '/_auth/profile': typeof AuthProfileRoute
  '/buyers/$buyerId': typeof BuyersBuyerIdRouteWithChildren
  '/sellers/$sellerId': typeof SellersSellerIdRouteWithChildren
  '/buyers/$buyerId/wood-piece-offers-list': typeof BuyersBuyerIdWoodPieceOffersListRoute
  '/sellers/$sellerId/wood-pieces-list': typeof SellersSellerIdWoodPiecesListRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | ''
    | '/buyers'
    | '/login'
    | '/sellers'
    | '/profile'
    | '/buyers/$buyerId'
    | '/sellers/$sellerId'
    | '/buyers/$buyerId/wood-piece-offers-list'
    | '/sellers/$sellerId/wood-pieces-list'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | ''
    | '/buyers'
    | '/login'
    | '/sellers'
    | '/profile'
    | '/buyers/$buyerId'
    | '/sellers/$sellerId'
    | '/buyers/$buyerId/wood-piece-offers-list'
    | '/sellers/$sellerId/wood-pieces-list'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/buyers'
    | '/login'
    | '/sellers'
    | '/_auth/profile'
    | '/buyers/$buyerId'
    | '/sellers/$sellerId'
    | '/buyers/$buyerId/wood-piece-offers-list'
    | '/sellers/$sellerId/wood-pieces-list'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  BuyersRoute: typeof BuyersRouteWithChildren
  LoginRoute: typeof LoginRoute
  SellersRoute: typeof SellersRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  BuyersRoute: BuyersRouteWithChildren,
  LoginRoute: LoginRoute,
  SellersRoute: SellersRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_auth",
        "/buyers",
        "/login",
        "/sellers"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/_auth": {
      "filePath": "_auth.tsx",
      "children": [
        "/_auth/profile"
      ]
    },
    "/buyers": {
      "filePath": "buyers.tsx",
      "children": [
        "/buyers/$buyerId"
      ]
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/sellers": {
      "filePath": "sellers.tsx",
      "children": [
        "/sellers/$sellerId"
      ]
    },
    "/_auth/profile": {
      "filePath": "_auth.profile.tsx",
      "parent": "/_auth"
    },
    "/buyers/$buyerId": {
      "filePath": "buyers/$buyerId.tsx",
      "parent": "/buyers",
      "children": [
        "/buyers/$buyerId/wood-piece-offers-list"
      ]
    },
    "/sellers/$sellerId": {
      "filePath": "sellers/$sellerId.tsx",
      "parent": "/sellers",
      "children": [
        "/sellers/$sellerId/wood-pieces-list"
      ]
    },
    "/buyers/$buyerId/wood-piece-offers-list": {
      "filePath": "buyers/$buyerId/wood-piece-offers-list.tsx",
      "parent": "/buyers/$buyerId"
    },
    "/sellers/$sellerId/wood-pieces-list": {
      "filePath": "sellers/$sellerId/wood-pieces-list.tsx",
      "parent": "/sellers/$sellerId"
    }
  }
}
ROUTE_MANIFEST_END */
